# This is a basic workflow to help you get started with Actions

name: AzureDeploy

env:
  # This is the global resource prefix for this deployment
  # Use lower case letters and numbers only
  DEPLOYMENT_NAME: "nbredir"

  # Azure region to which the resources will be deployed
  DEPLOYMENT_REGION: "westeurope"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true 
        
        - name: 'Repository Login'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.AZURE_ACR_REGISTRY }}
            username: ${{ secrets.AZURE_ACR_USERNAME }}
            password: ${{ secrets.AZURE_ACR_PASSWORD }}
          
        - name: Build and Push Image
          run: |
            cd app
            docker build . -t ${{ secrets.AZURE_ACR_REGISTRY }}/redirector:${{ github.sha }}
            docker push ${{ secrets.AZURE_ACR_REGISTRY }}/redirector:${{ github.sha }}

        - name: Deploy Azure Resources
          uses: azure/powershell@v1
          with: 
            inlineScript: |
              $params = @{
                customDomain = "${{ secrets.AZUREDEPLOY_CUSTOM_DOMAIN }}";
                name = "${{env.DEPLOYMENT_NAME}}";
                containerImage = "${{ secrets.AZURE_ACR_REGISTRY }}/redirector:${{ github.sha }}";
                acrServer = "${{ secrets.AZURE_ACR_REGISTRY }}";
                acrUser = "${{ secrets.AZURE_ACR_USERNAME }}";
                acrPassword = "${{ secrets.AZURE_ACR_PASSWORD }}";
              }

              $resourceGroup = "${{ secrets.AZUREDEPLOY_RESOURCEGROUP }}"
              $res = New-AzDeployment -Name ${{env.DEPLOYMENT_NAME}} -TemplateFile "template/main.bicep" -TemplateParameterObject $params -Location ${{env.DEPLOYMENT_REGION}}
              $res.ProvisioningState

            azPSVersion: '3.1.0'
