# This is a basic workflow to help you get started with Actions

name: AzureDeploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Docker Build and Push
        uses: azure/docker-login@v1
        with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}.azurecr.io
            username: ${{ secrets.AZURE_ACR_USERNAME }}
            password: ${{ secrets.AZURE_ACR_PASSWORD }}
      - run: |
          cd app
          docker build . -t ${{ secrets.AZURE_ACR_REGISTRY }}.azurecr.io/${{ secrets.AZURE_ACR_REPOSITORY }}:${{ github.sha }}
          docker push ${{ secrets.AZURE_ACR_REGISTRY }}.azurecr.io/${{ secrets.AZURE_ACR_REPOSITORY }}:${{ github.sha }}
